name: Build LKM for Re:Kernel
on:
  push:
    paths:
      - 'LKM-Source/**'
      - '.github/workflows/ddk-lkm.yml'
      - '.github/workflows/build-lkm.yml'
  workflow_dispatch:
jobs:
  build-lkm:
    strategy:
      matrix:
        include:
          - kmi: android12-5.10
            ddk_release: '20260313'
          - kmi: android13-5.10
            ddk_release: '20260313'
          - kmi: android13-5.15
            ddk_release: '20260313'
          - kmi: android14-5.15
            ddk_release: '20260313'
          - kmi: android14-6.1
            ddk_release: '20250825'
          - kmi: android14-6.1
            ddk_release: '20260313'
          - kmi: android15-6.6
            ddk_release: '20260313'
          - kmi: android16-6.12
            ddk_release: '20251104'
          - kmi: android16-6.12
            ddk_release: '20260313'
    uses: ./.github/workflows/ddk-lkm.yml
    with:
      kmi: ${{ matrix.kmi }}
      ddk_release: ${{ matrix.ddk_release }}
