name: Build Re:Kernel Kernel Module

on:
  workflow_call:
    inputs:
      kmi:
        description: 'KMI version'
        required: true
        type: string
      ddk_release:
        description: 'DDK release version'
        required: false
        default: '20260313'
        type: string
      version:
        description: 'Re:Kernel version'
        required: false
        default: 'snapshot'
        type: string

jobs:
  build-rekernel-ko:
    name: Build rekernel.ko for ${{ inputs.kmi }}-${{ inputs.ddk_release }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ylarod/ddk:${{ inputs.kmi }}-${{ inputs.ddk_release }}
      options: --privileged

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Build rekernel.ko
        run: |
          
          KMI=${{ inputs.kmi }}
          
          echo "=== Building rekernel.ko for KMI: $KMI ==="

          # sources -> in-tree binder dir (skip Makefile/Kconfig/README)
          cp ./LKM-Source/*.c ./LKM-Source/*.h /opt/ddk/src/$KMI/drivers/android/
          cat ./LKM-Source/Makefile >> /opt/ddk/src/$KMI/drivers/android/Makefile

          # Build
          cd /opt/ddk/src/$KMI
          make -C /opt/ddk/kdir/$KMI \
            M=/opt/ddk/src/$KMI/drivers/android \
            CONFIG_REKERNEL=m \
            CC="clang" \
            REKERNEL_VERSION="${{ inputs.version }}" \
            modules

          echo "=== Build completed ==="

          # Artifact
          mkdir -p /github/workspace/out
          OUTPUT_NAME="rekernel-${{ inputs.kmi }}-${{ inputs.ddk_release }}.ko"
          cp /opt/ddk/src/$KMI/drivers/android/rekernel.ko "/github/workspace/out/$OUTPUT_NAME"
          llvm-strip -d "/github/workspace/out/$OUTPUT_NAME"
          ls -la "/github/workspace/out/$OUTPUT_NAME"

      - name: Upload rekernel.ko artifact
        uses: actions/upload-artifact@v7
        with:
          name: rekernel-${{ inputs.kmi }}-${{ inputs.ddk_release }}.ko
          path: /github/workspace/out/rekernel-${{ inputs.kmi }}-${{ inputs.ddk_release }}.ko
